apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}-deployment
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}-app
  template:
    metadata:
      labels:
        app: ${APP_NAME}-app
    spec:
      containers:
      - name: ${APP_NAME}-container
        image: k8s-vga-worker1:5000/${TEAM_PREFIX}-${APP_NAME}:v${VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 9206
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: ${APP_NAME}-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9206
      nodePort: ${NODE_PORT}
  type: NodePort
