# team3 spring-boot service with mysql
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service-by-jenkins
  namespace: group1-team3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-service-by-jenkins
  template:
    metadata:
      labels:
        app: accounts-service-by-jenkins
    spec:
      containers:
      - name: accounts-service-by-jenkins
        image: k8s-vga-worker1:5000/group1-team3-accounts-service-by-jenkins:latest
        imagePullPolicy: Always #IfNotPresent
        ports:
        - containerPort: 9095
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service-by-jenkins
  namespace: group1-team3
spec:
  selector:
    app: accounts-service-by-jenkins
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9095
      nodePort: 30311
  type: NodePort

