apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-deployment
  namespace: group1-team3
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cards-app
  template:
    metadata:
      labels:
        app: cards-app
    spec:
      containers:
      - name: cards-container
        image: k8s-vga-worker1:5000/group1-team3-cards:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9207
---
apiVersion: v1
kind: Service
metadata:
  name: cards-service
  namespace: group1-team3
spec:
  selector:
    app: cards-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9207
      nodePort: 30317
  type: NodePort
