apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans-deployment
  namespace: group1-team3
spec:
  replicas: 4
  selector:
    matchLabels:
      app: loans-app
  template:
    metadata:
      labels:
        app: loans-app
    spec:
      containers:
      - name: loans-container
        image: k8s-vga-worker1:5000/group1-team3-loans:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9208
---
apiVersion: v1
kind: Service
metadata:
  name: loans-service
  namespace: group1-team3
spec:
  selector:
    app: loans-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9208
      nodePort: 30318
  type: NodePort
