server:
  port: 9203

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      # defaultZone: http://localhost:8070/eureka/
      defaultZone: http://eurekaserver-service:80/eureka/
