apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  namespace: group1-team3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver-app
  template:
    metadata:
      labels:
        app: configserver-app
    spec:
      containers:
      - name: configserver-container
        image: k8s-vga-worker1:5000/group1-team3-configserver:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  name: configserver-service
  namespace: group1-team3
spec:
  selector:
    app: configserver-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9100
      nodePort: 30310
  type: NodePort
